<?php

/**
 * @file
 * Contains si_funraiseup.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

function si_fundraiseup_theme() {
  return [
    'fundraiseup_js' => [
      'variables' => [
        'code' => NULL
      ],
    ],
  ];
}


function si_fundraiseup_page_top(array &$page) {
  $config = \Drupal::service('config.factory')->get('si_fundraiseup.settings');
  if ($code = $config->get('code')) {
    $page['si_fundraiseup_script'][] = [
      '#theme' => 'fundraiseup_js',
      '#code' => $code,
    ];
  }
}
