<?php

/**
 * @file
 * Contains si_funraiseup.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

function si_fundraiseup_theme() {
  return [
    'fundraiseup_js' => [
      'variables' => [
        'code' => NULL
      ],
    ],
  ];
}


function si_fundraiseup_page_top(array &$page) {
  $config = \Drupal::service('config.factory')->get('si_fundraiseup.settings');
  if ($code = $config->get('code')) {
    $page['si_fundraiseup_script'][] = [
      '#theme' => 'fundraiseup_js',
      '#code' => $code,
    ];
  }
}

//function si_fundraiseup_page_attachments(array &$attachments) {
//	$config = \Drupal::service('config.factory')->get('si_fundraiseup.settings');
//
//	if ($code = $config->get('code')) {
//		$attachments['#attached']['html_head'][] = [
//			[
//				'#tag' => 'script',
//				'#value' => "(function(w,d,s,n,a){if(!w[n]){var l='call,catch,on,once,set,then,track,openCheckout'
//.split(','),i,o=function(n){return'function'==typeof n?o.l.push([arguments])&&o
//:function(){return o.l.push([n,arguments])&&o}},t=d.getElementsByTagName(s)[0],
//j=d.createElement(s);j.async=!0;j.src='https://cdn.fundraiseup.com/widget/'+a+'';
//t.parentNode.insertBefore(j,t);o.s=Date.now();o.v=5;o.h=w.location.href;o.l=[];
//for(i=0;i<8;i++)o[l[i]]=o(l[i]);w[n]=o}
//})(window,document,'script','FundraiseUp','". $code."');",
//			],
//			'si_fundraiseup_script',
//		];
//	}
//}
